language: swift
osx_image: xcode9.3

branches:
  only:
    - master
    - develop

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - xcodebuild clean build -project r2-streamer-swift.xcodeproj -scheme r2-streamer-swift -destination "platform=iOS Simulator,name=iPhone 8,OS=11.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
